name: SPFx CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.14.0'

    - name: Install dependencies
      run: |
        npm install -g gulp
        npm install

    - name: Run tests
      run: |
        npm test

    - name: Bundle and package SPFx solution
      run: |
        gulp bundle --ship
        gulp package-solution --ship

    - name: Upload .sppkg
      uses: actions/upload-artifact@v2
      with:
        name: sppkg
        path: sharepoint/solution/*.sppkg

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download .sppkg
      uses: actions/download-artifact@v2
      with:
        name: sppkg
        path: ./solution

    - name: Deploy sppkg to SharePoint App Catalog
      env:
        APP_CATALOG_URL: ${{ secrets.APP_CATALOG_URL }}
        SHAREPOINT_USERNAME: ${{ secrets.SHAREPOINT_USERNAME }}
        SHAREPOINT_PASSWORD: ${{ secrets.SHAREPOINT_PASSWORD }}
      run: |
        npm install -g @pnp/cli-microsoft365
        m365 login --authType password --userName ${{ secrets.SHAREPOINT_USERNAME }} --password ${{ secrets.SHAREPOINT_PASSWORD }}
        m365 spo app add --filePath ./solution/*.sppkg --appCatalogUrl ${{ secrets.APP_CATALOG_URL }} --overwrite
        m365 spo app deploy --name *.sppkg --appCatalogUrl ${{ secrets.APP_CATALOG_URL }}
